# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step: 
         name: Deploy to AWS
         deployment: production
         image: atlassian/pipelines-awscli
         script:
          - ls -la 
          - aws deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/helloworld.zip --no-ignore-hidden-files
          - aws deploy create-deployment --application-name $APPLICATION_NAME --deployment-config-name $DEPLOYMENT_CONFIG --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$S3_BUCKET,key=helloworld.zip,bundleType=zip